version: "3.9"

services:
  judge:
    build:
      context: ./judge
    image: shodhaicode/judge:latest
    command: ["sleep", "infinity"]

  backend:
    build:
      context: ./backend
    environment:
      - SPRING_PROFILES_ACTIVE=default
      - JUDGE_IMAGE=shodhaicode/judge:latest
      - JUDGE_USE_DOCKER=true
      - JUDGE_WORKSPACE_ROOT=/judge/workspaces
    volumes:
      - judge-workspaces:/judge/workspaces
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8081:8081"
    depends_on:
      - judge

  frontend:
    build:
      context: ./frontend
    environment:
      - NEXT_PUBLIC_API_BASE_URL=http://backend:8081
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  judge-workspaces:
